services:
  backend:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    ports:
      - "5044:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tododb;Username=postgres;Password=ToDo_321

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ToDo_321
      POSTGRES_DB: tododb

  frontend:
    build:
      context: ./todo-ui
      dockerfile: Dockerfile
    ports:
      - "5100:80"
